-- ============================================================
-- seed_demo_reviews.sql
-- 155 demo reviews across 50 cleaners
-- Distribution: ~60% 5-star, ~25% 4-star, ~10% 3-star, ~5% 1-2 star
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `reviews` (`cleaner_id`, `user_id`, `author_name`, `author_email`, `rating`, `title`, `content`, `status`, `is_verified`, `created_at`) VALUES

-- ============================================================
-- Sunshine Roofing Co. (12 reviews: 8x5, 3x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Jennifer Adams', 'jadams@email.com', 5, 'Excellent roof replacement', 'Carlos and his team replaced our entire tile roof after Hurricane Irma damage. They handled our insurance claim paperwork and completed the work in just four days. The roof looks amazing and we haven''t had a single leak since.', 'approved', 1, '2025-08-15 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Robert Chen', 'rchen@email.com', 5, 'Professional and fast', 'Had a major leak during a storm and Sunshine Roofing came out the same day. They tarped the roof immediately and scheduled the full repair for the following week. Great communication throughout the entire process.', 'approved', 1, '2025-09-02 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Lisa Martinez', 'lmartinez@email.com', 5, 'Best roofing company in Miami', 'We got quotes from five different roofers and Sunshine offered the best value. Their crew was hardworking, respectful, and cleaned up everything when they were done. Highly recommend to anyone in South Florida.', 'approved', 1, '2025-09-20 09:45:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Thomas Walker', 'twalker@email.com', 4, 'Good work, minor delay', 'The quality of the roof installation is excellent and we are very happy with the final result. Only reason for four stars is the project started two days later than originally scheduled due to a parts delay.', 'approved', 1, '2025-10-05 16:00:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Amanda Foster', 'afoster@email.com', 5, 'Trustworthy and skilled', 'Sunshine Roofing diagnosed a ventilation problem that two other companies missed. They fixed the issue and our attic is noticeably cooler now. Fair pricing and honest assessment of what we actually needed.', 'approved', 1, '2025-10-18 11:20:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'David Park', 'dpark@email.com', 5, 'Outstanding storm repair', 'After a bad thunderstorm knocked off some tiles, these guys were on my roof the next morning. Quick, thorough, and the repair is seamless. You can''t even tell where the damage was.', 'approved', 1, '2025-11-01 08:45:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Sarah Mitchell', 'smitchell@email.com', 4, 'Very satisfied', 'They replaced our old shingle roof with a beautiful new tile roof. The transformation is incredible and our neighbors keep asking who we used. Communication could have been slightly better during the project.', 'approved', 1, '2025-11-15 13:30:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Kevin Brooks', 'kbrooks@email.com', 5, 'Five stars all around', 'From the initial estimate to the final inspection, Sunshine Roofing was professional and transparent. The crew leader explained every step of the process and the workmanship is top-notch.', 'approved', 1, '2025-12-03 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Patricia Young', 'pyoung@email.com', 5, 'Highly recommend', 'We hired them for a complete re-roof and they delivered exactly what was promised. Great attention to detail on the flashing and ventilation. Clean worksite every evening.', 'approved', 1, '2025-12-20 15:45:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Brian Turner', 'bturner@email.com', 4, 'Solid roofing work', 'Good quality installation of architectural shingles on our home. The price was competitive and the 10-year workmanship warranty gives us great peace of mind.', 'approved', 1, '2026-01-08 09:15:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Nancy White', 'nwhite@email.com', 5, 'Saved us from a disaster', 'Discovered our roof decking was rotting during what we thought would be a simple repair. They showed us photos, explained the options, and replaced the damaged sections without trying to upsell us on a full roof.', 'approved', 1, '2026-01-22 12:00:00'),
((SELECT id FROM cleaners WHERE slug = 'sunshine-roofing-co'), NULL, 'Mark Phillips', 'mphillips@email.com', 3, 'Decent but took longer than expected', 'The final result is good and the roof looks nice. However, the project took eight days instead of the estimated five. Workers were friendly but the scheduling could be improved.', 'approved', 1, '2026-02-05 14:30:00'),

-- ============================================================
-- Metro Plumbing Solutions (8 reviews: 5x5, 2x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Angela Rivera', 'arivera@email.com', 5, 'Fixed our burst pipe fast', 'Pipe burst in our kitchen at 11 PM and Metro had a plumber at our door within 45 minutes. He stopped the flooding, repaired the pipe, and helped us clean up. Absolute lifesaver.', 'approved', 1, '2025-08-22 23:30:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'William Foster', 'wfoster@email.com', 5, 'Great water heater install', 'James and his team replaced our old 40-gallon tank with a tankless system. They explained the energy savings we could expect and the installation was completed in one day. Very professional.', 'approved', 1, '2025-09-10 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Christine Hall', 'chall@email.com', 4, 'Good service, honest pricing', 'Called them for a clogged shower drain and the plumber was upfront about the cost before starting any work. Fixed the issue in about 30 minutes. Will definitely call again.', 'approved', 1, '2025-10-15 08:30:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Daniel Brown', 'dbrown@email.com', 5, 'Bathroom plumbing done right', 'Metro Plumbing handled all the rough-in plumbing for our bathroom renovation. Everything was done to code and they coordinated perfectly with our general cleaner. No issues at inspection.', 'approved', 1, '2025-11-08 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Rachel Green', 'rgreen@email.com', 5, 'Reliable and reasonably priced', 'We have used Metro Plumbing three times now for various repairs and they have been excellent every time. Consistent quality, fair prices, and they always show up when they say they will.', 'approved', 1, '2025-12-01 10:15:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Gary Adams', 'gadams@email.com', 4, 'Solved a tricky drain issue', 'Had a recurring drain clog that another plumber couldn''t fix. Metro used a camera to find tree roots in the line and cleared them out with a hydro jet. Problem solved for good.', 'approved', 1, '2025-12-18 15:00:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Stephanie Lee', 'slee@email.com', 5, 'Emergency service when we needed it', 'Our toilet overflowed on a Saturday evening and they came within an hour. Fixed the issue quickly and the plumber was very polite and cleaned up after himself.', 'approved', 1, '2026-01-12 18:30:00'),
((SELECT id FROM cleaners WHERE slug = 'metro-plumbing-solutions'), NULL, 'Howard Clark', 'hclark@email.com', 3, 'Took a while to get an appointment', 'The actual plumbing work was good quality, but it took over a week to get scheduled for a non-emergency repair. Once they arrived, the plumber was knowledgeable and efficient.', 'approved', 1, '2026-02-01 09:00:00'),

-- ============================================================
-- Coastal Kitchen & Bath (10 reviews: 7x5, 2x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Michelle Thompson', 'mthompson@email.com', 5, 'Dream kitchen came true', 'Maria and her design team completely transformed our dated kitchen into a modern masterpiece. The quartz countertops, soft-close cabinets, and tile backsplash are absolutely gorgeous. Worth every penny.', 'approved', 1, '2025-08-10 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Jeffrey Scott', 'jscott@email.com', 5, 'Stunning bathroom renovation', 'Our master bathroom went from an 80s disaster to a spa-like retreat. The frameless glass shower, heated floors, and freestanding tub are exactly what we wanted. The team was meticulous about every detail.', 'approved', 1, '2025-09-05 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Laura Anderson', 'landerson@email.com', 5, 'Best remodeler in Broward', 'This is the second time we have used Coastal Kitchen & Bath and both experiences have been outstanding. They just finished our guest bathroom and it looks like something out of a magazine.', 'approved', 1, '2025-09-25 16:45:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Charles Wright', 'cwright@email.com', 4, 'Beautiful kitchen, slight delay', 'The finished kitchen is absolutely beautiful and the quality of the cabinetry is exceptional. The project ran about 10 days over the original timeline, but the end result made the wait worthwhile.', 'approved', 1, '2025-10-12 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Diana Patel', 'dpatel@email.com', 5, 'Outstanding design and execution', 'Their designer helped us maximize our small kitchen space in ways we never imagined. The layout is so much more functional now and the modern design makes the room feel twice as big.', 'approved', 1, '2025-11-03 13:15:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'George Kim', 'gkim@email.com', 5, 'Exceeded our expectations', 'We hired them to remodel both our kitchen and master bath. The coordination between the two projects was seamless and the quality of work is exceptional. Our home feels brand new.', 'approved', 1, '2025-11-20 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Karen Fisher', 'kfisher@email.com', 5, 'Professional from start to finish', 'The entire process was smooth from the initial design meeting to the final walkthrough. They protected our floors, cleaned up daily, and the finished bathroom is absolutely stunning.', 'approved', 1, '2025-12-08 15:30:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Ryan Nelson', 'rnelson@email.com', 4, 'Great craftsmanship', 'Really happy with our new kitchen countertops and tile work. The installation crew was skilled and careful. Minor communication gaps with scheduling but overall a very positive experience.', 'approved', 1, '2025-12-28 12:00:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Samantha Cruz', 'scruz@email.com', 5, 'Worth the investment', 'We compared several remodeling companies and chose Coastal for their portfolio and reviews. They delivered exactly the high-end kitchen renovation we were looking for. Absolutely love it.', 'approved', 1, '2026-01-15 10:45:00'),
((SELECT id FROM cleaners WHERE slug = 'coastal-kitchen-and-bath'), NULL, 'Thomas Reed', 'treed@email.com', 3, 'Good quality but over budget', 'The workmanship is excellent and our bathroom looks great. However, several change orders during the project pushed the final cost about 15% over the original estimate. Make sure to budget extra.', 'approved', 1, '2026-02-02 14:00:00'),

-- ============================================================
-- Florida Comfort HVAC (7 reviews: 4x5, 2x4, 1x2)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Jessica Morgan', 'jmorgan@email.com', 5, 'New AC works perfectly', 'Our 15-year-old AC finally gave out in July and Florida Comfort had a new Carrier system installed within two days. The house is cool again and our electric bill dropped by about $60 a month.', 'approved', 1, '2025-08-25 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Marcus Johnson', 'mjohnson@email.com', 5, 'Same-day AC repair', 'AC stopped blowing cold air on a 95-degree day. Their tech arrived within three hours, diagnosed a bad capacitor, and had it replaced in under an hour. Back to cool in no time.', 'approved', 1, '2025-09-30 16:30:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Emily Davis', 'edavis@email.com', 4, 'Good maintenance service', 'We signed up for their annual maintenance plan and the technician was thorough during the tune-up. He found a small refrigerant leak and fixed it before it became a bigger problem.', 'approved', 1, '2025-10-22 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Vincent Rossi', 'vrossi@email.com', 5, 'Excellent duct cleaning', 'Had our ducts cleaned and what they pulled out was shocking. The air quality in our home improved immediately and my allergies have been much better since. Very thorough job.', 'approved', 1, '2025-11-14 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Carol Sanders', 'csanders@email.com', 4, 'Reliable and knowledgeable', 'David''s team installed a new heat pump system in our home. They explained the pros and cons of different options and helped us choose the right size system. Good value for the money.', 'approved', 1, '2025-12-10 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Nathan Price', 'nprice@email.com', 5, 'Fixed it right the first time', 'Multiple companies couldn''t figure out why our AC kept short-cycling. Florida Comfort found a bad expansion valve on the first visit. AC has been running perfectly ever since.', 'approved', 1, '2026-01-05 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'florida-comfort-hvac'), NULL, 'Diana Cooper', 'dcooper@email.com', 2, 'Expensive repair', 'The technician was knowledgeable but the repair bill was significantly higher than what I was quoted on the phone. I felt pressured into additional services that may not have been necessary.', 'approved', 1, '2026-01-28 11:00:00'),

-- ============================================================
-- Palm City Electrical (5 reviews: 3x5, 1x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'palm-city-electrical'), NULL, 'Robert Harris', 'rharris@email.com', 5, 'Panel upgrade done professionally', 'Needed to upgrade from a 100-amp to 200-amp panel for our home office. The electrician was incredibly knowledgeable, pulled all permits, and passed inspection on the first try.', 'approved', 1, '2025-09-15 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'palm-city-electrical'), NULL, 'Amy Peterson', 'apeterson@email.com', 5, 'Smart home wiring experts', 'They wired our entire house for a smart home system including automated lighting, motorized blinds, and a whole-house audio system. Everything works flawlessly and the wiring is immaculate.', 'approved', 1, '2025-11-10 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'palm-city-electrical'), NULL, 'Frank Rodriguez', 'frodriguez@email.com', 4, 'Good work on generator install', 'Had a whole-house Generac generator installed and the team did a solid job. They handled the gas line, electrical connections, and city permit. Only took three days start to finish.', 'approved', 1, '2025-12-15 09:45:00'),
((SELECT id FROM cleaners WHERE slug = 'palm-city-electrical'), NULL, 'Beth Young', 'byoung@email.com', 5, 'Emergency repair at midnight', 'Half our house lost power at midnight and Palm City had an electrician out within an hour. Turned out to be a failed breaker. Quick fix and they only charged a reasonable emergency fee.', 'approved', 1, '2026-01-10 00:30:00'),
((SELECT id FROM cleaners WHERE slug = 'palm-city-electrical'), NULL, 'Steve Martinez', 'smartinez@email.com', 3, 'Decent work, scheduling issues', 'The electrical work itself was good quality, but they had to reschedule our appointment twice. Once they showed up, the work was done efficiently and everything passed inspection.', 'approved', 1, '2026-02-08 11:15:00'),

-- ============================================================
-- Tampa Bay Bath Remodeling (6 reviews: 3x5, 2x4, 1x2)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'Kelly Adams', 'kadams@email.com', 5, 'Beautiful walk-in shower', 'They converted our old tub into a gorgeous walk-in shower with a rain head and bench. The tile work is perfect and the frameless glass door really opens up the space. Done in just six days.', 'approved', 1, '2025-09-08 12:00:00'),
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'James Potter', 'jpotter@email.com', 4, 'Good bathroom update', 'New vanity, toilet, mirror, and lighting fixtures have completely updated our guest bathroom. The work was done well and the crew kept the rest of the house clean during the project.', 'approved', 1, '2025-10-20 15:30:00'),
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'Nicole Washington', 'nwashington@email.com', 5, 'ADA bathroom for my parents', 'They built an accessible bathroom for my elderly parents with grab bars, a zero-threshold shower, and a comfort-height toilet. Thoughtful design and the team was patient and caring.', 'approved', 1, '2025-11-22 10:45:00'),
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'Craig Morrison', 'cmorrison@email.com', 5, 'Exactly what we wanted', 'After getting five quotes, we went with Tampa Bay Bath and could not be happier. The custom vanity and tile work exceeded our expectations. Great value for the quality of work.', 'approved', 1, '2025-12-30 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'Helen Brooks', 'hbrooks@email.com', 4, 'Nice remodel, minor punch list', 'Overall very happy with our new bathroom. There were a few small punch list items after the project was done, but they came back and took care of everything within a week.', 'approved', 1, '2026-01-18 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'tampa-bay-bath-remodeling'), NULL, 'Victor Diaz', 'vdiaz@email.com', 2, 'Disappointed with communication', 'The bathroom looks nice but communication during the project was poor. Had to call multiple times to get updates and the project manager was hard to reach. The workers themselves were skilled.', 'approved', 1, '2026-02-10 16:00:00'),

-- ============================================================
-- First Coast General Contracting (9 reviews: 6x5, 2x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Amanda Richardson', 'arichardson@email.com', 5, 'Room addition was perfect', 'Michael and his team built a 400 sq ft addition for our growing family. The new room matches the existing house perfectly and the construction quality is top-notch. On time and on budget.', 'approved', 1, '2025-08-20 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Dennis Clark', 'dclark@email.com', 5, 'Built our dream home', 'First Coast GC managed the entire construction of our custom home. The project management was exceptional with weekly updates, transparent budgeting, and proactive problem-solving.', 'approved', 1, '2025-09-15 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Rebecca Taylor', 'rtaylor@email.com', 5, 'Kitchen remodel exceeded expectations', 'We hired them to open up our kitchen into the living room and the result is stunning. They handled structural engineering, permitting, and all the subcleaners. Seamless process.', 'approved', 1, '2025-10-08 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Paul Yang', 'pyang@email.com', 4, 'Solid commercial buildout', 'They completed the buildout of our dental office space and it looks great. A couple of minor change orders added to the cost, but the final product was exactly what we needed.', 'approved', 1, '2025-11-01 13:00:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Sandra Cooper', 'scooper@email.com', 5, 'Wonderful renovation experience', 'Renovated our 1960s ranch home and it feels like a brand new house. New layout, new systems, new everything. The crew was respectful of our property and kept the site clean.', 'approved', 1, '2025-11-25 09:15:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Jerome Walker', 'jwalker@email.com', 5, 'True professionals', 'From the detailed proposal to the final punch list walkthrough, this company operates at a high level. Their project manager kept us informed at every stage and the quality speaks for itself.', 'approved', 1, '2025-12-12 15:30:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Monica Reed', 'mreed@email.com', 4, 'Great results, minor delays', 'The whole-house renovation turned out beautifully. There were some scheduling delays with subcleaners but the GC managed them well and the final quality was excellent.', 'approved', 1, '2026-01-04 11:45:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Harold Grant', 'hgrant@email.com', 5, 'Garage conversion done right', 'They converted our two-car garage into a mother-in-law suite with a kitchenette and full bath. Everything was permitted and inspected. The finished space is beautiful and functional.', 'approved', 1, '2026-01-22 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'first-coast-general-contracting'), NULL, 'Tracy Mills', 'tmills@email.com', 3, 'Good work but communication gaps', 'The construction quality is excellent but there were periods where we had trouble getting updates on progress. A more proactive communication approach would have made this a five-star experience.', 'approved', 1, '2026-02-08 14:00:00'),

-- ============================================================
-- Bay Area Roofing Pros (15 reviews: 10x5, 4x4, 1x3)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Catherine Lee', 'clee@email.com', 5, 'The best roofer in the Bay Area', 'William and his team replaced the slate roof on our Victorian home and it looks spectacular. They sourced matching slate tiles and the craftsmanship is museum-quality. Could not be happier.', 'approved', 1, '2025-08-05 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Andrew Watson', 'awatson@email.com', 5, 'Flat roof experts', 'Had a persistent leak on our flat commercial roof that three other companies couldn''t fix. Bay Area Roofing found the problem in 20 minutes and installed a new TPO membrane. Leak gone forever.', 'approved', 1, '2025-08-28 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Margaret Chen', 'mchen@email.com', 5, 'Incredible green roof', 'They installed a green roof system on our eco-friendly office building. The plants are thriving and our energy bills have dropped. A truly unique offering in the Bay Area.', 'approved', 1, '2025-09-12 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Scott Wilson', 'swilson@email.com', 4, 'Excellent quality work', 'New composition shingle roof looks great and was installed quickly. The price was a bit higher than some quotes we received, but the workmanship and warranty justify the investment.', 'approved', 1, '2025-09-28 12:15:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Diana Foster', 'dfoster@email.com', 5, 'Saved our home from water damage', 'Found extensive hidden water damage during a routine inspection. They repaired all the damaged decking before installing the new roof and probably saved us tens of thousands in future repairs.', 'approved', 1, '2025-10-15 16:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'John Mitchell', 'jmitchell@email.com', 5, 'Professional crew, great results', 'Five-man crew completed our re-roof in three days. They were organized, efficient, and left our yard cleaner than they found it. The new architectural shingles look stunning.', 'approved', 1, '2025-10-30 10:45:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Rachel Kim', 'rkim@email.com', 4, 'Very good experience overall', 'Had some skylights added along with a new roof. The integration is seamless and the natural light in our home is wonderful now. Minor scheduling hiccup but nothing major.', 'approved', 1, '2025-11-18 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Michael Santos', 'msantos@email.com', 5, 'Top-notch tile roofing', 'They installed a clay tile roof on our Mediterranean-style home. The attention to detail on the ridge caps and valleys is exceptional. This roof will last a lifetime.', 'approved', 1, '2025-12-02 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Laura Peters', 'lpeters@email.com', 5, 'Repeat customer, always happy', 'This is the third property where I have used Bay Area Roofing. Consistently excellent work, transparent pricing, and they stand behind their warranty. The gold standard for roofers.', 'approved', 1, '2025-12-18 09:15:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Brandon Hill', 'bhill@email.com', 5, 'Emergency tarping saved us', 'Tree fell on our roof during a windstorm and they had a tarp on it within two hours. The permanent repair was scheduled the following week and done perfectly. Grateful for their fast response.', 'approved', 1, '2026-01-06 08:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Susan Taylor', 'staylor@email.com', 4, 'Solid commercial roofing', 'They replaced the EPDM roof on our warehouse. The work was done on weekends to avoid disrupting our business operations. Good communication and quality work.', 'approved', 1, '2026-01-15 13:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Allen Davis', 'adavis@email.com', 5, 'Best warranty in the business', 'They offer a 10-year workmanship warranty on top of the manufacturer warranty. That level of confidence in their work says a lot. The roof looks amazing too.', 'approved', 1, '2026-01-25 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Jennifer White', 'jwhite@email.com', 5, 'Outstanding service', 'Bay Area Roofing Pros is the most professional roofing company we have ever worked with. From the drone inspection to the final walkthrough, every step was handled with care.', 'approved', 1, '2026-02-01 15:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Robert Brown', 'rbrown2@email.com', 4, 'Good roof, fair price', 'Replaced our 25-year-old roof with new 30-year architectural shingles. The crew was hardworking and efficient. Price was middle of the road compared to other quotes.', 'approved', 1, '2026-02-08 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'bay-area-roofing-pros'), NULL, 'Elizabeth Moore', 'emoore@email.com', 3, 'Work quality is great, communication could improve', 'The roof itself is perfect and looks beautiful. My only complaint is that it was sometimes hard to get return calls from the office. The field crew was excellent though.', 'approved', 1, '2026-02-14 09:30:00'),

-- ============================================================
-- Pacific Plumbing & Drain (11 reviews: 7x5, 3x4, 1x1)
-- ============================================================
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Victoria Chang', 'vchang@email.com', 5, 'Sewer line replacement done right', 'Pacific Plumbing replaced our entire sewer line using trenchless technology. Minimal disruption to our yard and the job was done in two days. They even patched the small access hole perfectly.', 'approved', 1, '2025-08-12 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Ronald West', 'rwest@email.com', 5, 'Whole house repiping', 'Our 1960s home had original galvanized pipes that were corroding. Daniel and his crew repiped the entire house with PEX in three days. Water pressure is incredible now.', 'approved', 1, '2025-09-08 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Megan Park', 'mpark@email.com', 4, 'Fast and professional', 'Called for a clogged kitchen drain and the plumber had it cleared within an hour. He also checked the other drains while he was here at no extra charge. Good service.', 'approved', 1, '2025-09-25 09:45:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Timothy Brooks', 'tbrooks@email.com', 5, 'Tankless water heater experts', 'They installed a Rinnai tankless water heater and the difference is amazing. Endless hot water and a noticeable drop in our gas bill. The installation was clean and professional.', 'approved', 1, '2025-10-18 11:15:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Catherine Rivera', 'crivera@email.com', 5, 'Best plumber in LA', 'We have used Pacific Plumbing for years and they never disappoint. Most recently they replumbed our bathroom during a renovation and the work was flawless. Highly recommended.', 'approved', 1, '2025-11-05 13:30:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Donald Garcia', 'dgarcia@email.com', 4, 'Good hydro jetting service', 'Tree roots had invaded our main sewer line. Pacific Plumbing cleared everything out with their hydro jet and recommended a root barrier to prevent future intrusion. Smart solution.', 'approved', 1, '2025-11-28 15:45:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Sandra Turner', 'sturner@email.com', 5, 'Emergency gas leak response', 'Smelled gas in our kitchen and Pacific had a technician at our house within 30 minutes. Found and repaired the leak in the gas line to our stove. Could not ask for faster service.', 'approved', 1, '2025-12-14 19:00:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Eric Henderson', 'ehenderson@email.com', 5, 'Excellent commercial plumbing', 'They handle all the plumbing maintenance for our restaurant chain. Always responsive, professional, and they understand the urgency of commercial plumbing problems.', 'approved', 1, '2026-01-03 08:30:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Mary Coleman', 'mcoleman@email.com', 4, 'Solid bathroom rough-in', 'Pacific Plumbing handled the plumbing for our bathroom addition. All work passed inspection on the first try and the crew was neat and organized.', 'approved', 1, '2026-01-20 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Jason Mitchell', 'jmitchell2@email.com', 5, 'Fixed what others could not', 'Had a mystery leak behind our shower wall that two other plumbers missed. Pacific Plumbing used their camera system to find it immediately. Impressive diagnostic skills.', 'approved', 1, '2026-02-04 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'pacific-plumbing-and-drain'), NULL, 'Debra Foster', 'dfoster2@email.com', 1, 'Overcharged for simple repair', 'Was charged a very high price for what turned out to be a simple faucet replacement. The plumber was competent but the bill seemed inflated. Would have appreciated more transparency on pricing.', 'approved', 1, '2026-02-12 11:00:00'),

-- ============================================================
-- Remaining cleaners: 3-5 reviews each (abbreviated for space)
-- ============================================================

-- SoCal Pro Painting (4 reviews)
((SELECT id FROM cleaners WHERE slug = 'socal-pro-painting'), NULL, 'Lauren Mitchell', 'lmitchell@email.com', 5, 'Beautiful exterior paint job', 'Kevin and his crew repainted our entire exterior in three days. The prep work was thorough, the lines are crisp, and the color match is perfect. Our house looks brand new.', 'approved', 1, '2025-10-10 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'socal-pro-painting'), NULL, 'Peter Watson', 'pwatson@email.com', 5, 'Interior painting perfection', 'They painted our entire downstairs including trim and ceilings. The attention to detail on the cut-ins around windows and doors is impressive. Very neat and professional crew.', 'approved', 1, '2025-11-22 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'socal-pro-painting'), NULL, 'Marie Lee', 'mlee@email.com', 4, 'Good cabinet painting', 'Had our kitchen cabinets painted from oak to white and the transformation is dramatic. The finish is smooth with no brush marks. One area needed a touch-up which they handled promptly.', 'approved', 1, '2026-01-08 11:15:00'),
((SELECT id FROM cleaners WHERE slug = 'socal-pro-painting'), NULL, 'Tom Henderson', 'thenderson@email.com', 4, 'Solid painting service', 'Repainted three bedrooms and a hallway. Color consultation was helpful, the crew was on time, and the results look great. Fair pricing for the quality of work.', 'approved', 1, '2026-02-05 09:30:00'),

-- Golden State HVAC (6 reviews)
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Patrick Kelly', 'pkelly@email.com', 5, 'Energy efficient install', 'Brian recommended a high-SEER Lennox system for our home and our electric bills dropped by 40%. The installation was clean and they sealed all the ductwork properly.', 'approved', 1, '2025-09-05 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Nina Patel', 'npatel@email.com', 5, 'Ductless mini-split experts', 'Had three mini-split units installed for our home addition and they work beautifully. Each room has individual temperature control and the units are whisper-quiet.', 'approved', 1, '2025-10-20 13:30:00'),
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Gary Stone', 'gstone@email.com', 4, 'Good furnace replacement', 'Replaced our old furnace with a 96% efficient model. The technician was knowledgeable and the install was clean. Took a bit longer than expected but the result is great.', 'approved', 1, '2025-11-30 09:45:00'),
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Linda Morris', 'lmorris@email.com', 5, 'Smart thermostat setup', 'In addition to our AC tune-up, they installed and programmed a Nest thermostat. Now we can control the temperature from our phones and the learning feature is saving us money.', 'approved', 1, '2025-12-18 15:00:00'),
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Chris Adams', 'cadams@email.com', 4, 'Reliable service', 'Used them for our annual HVAC maintenance and they caught a cracked heat exchanger before it became dangerous. Grateful for their thorough inspection.', 'approved', 1, '2026-01-12 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'golden-state-hvac'), NULL, 'Donna Baker', 'dbaker@email.com', 5, 'Quick AC repair', 'Our AC compressor failed during a heat wave and they had a replacement installed the same day. Emergency service was responsive and reasonably priced.', 'approved', 1, '2026-02-03 16:45:00'),

-- Lone Star Roofing (10 reviews)
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Richard Garcia', 'rgarcia@email.com', 5, 'Hail damage repair experts', 'After a major hailstorm, Lone Star inspected our roof, documented all damage, and handled our insurance claim from start to finish. New roof installed in just two days.', 'approved', 1, '2025-08-18 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Barbara Wilson', 'bwilson@email.com', 5, 'Best roofing company in Houston', 'Mark and his team were outstanding from start to finish. They replaced our entire roof with impact-resistant shingles and even got us an insurance discount for the upgrade.', 'approved', 1, '2025-09-22 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Steve Thompson', 'sthompson@email.com', 5, 'Metal roof looks incredible', 'Always wanted a metal roof and Lone Star made it happen. Standing seam panels in charcoal gray look amazing on our ranch-style home. They said it will last 50+ years.', 'approved', 1, '2025-10-10 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Carol Anderson', 'canderson@email.com', 4, 'Great quality, fair price', 'Got four quotes for our roof replacement and Lone Star offered the best combination of quality materials and reasonable pricing. The crew was professional and efficient.', 'approved', 1, '2025-11-05 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Wayne Miller', 'wmiller@email.com', 5, 'Insurance claim handled perfectly', 'Lone Star guided us through the entire insurance claim process after wind damage. They met with the adjuster, documented everything, and we ended up with a beautiful new roof.', 'approved', 1, '2025-11-28 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Teresa Roberts', 'troberts@email.com', 5, 'Family-owned excellence', 'You can tell this is a family business because they treat every customer like family. Mark personally stopped by during the installation to check on quality. That level of care is rare.', 'approved', 1, '2025-12-15 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Keith Turner', 'kturner@email.com', 4, 'Solid commercial roof', 'They installed a TPO system on our strip mall. Good quality work, proper drainage, and they coordinated with tenants to minimize disruption. Would use again.', 'approved', 1, '2026-01-05 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Janet Cruz', 'jcruz@email.com', 5, 'Storm damage pros', 'These guys are the ones to call after a Texas storm. Fast response, thorough damage assessment, and quality repairs. They even covered the damaged areas same day to prevent further issues.', 'approved', 1, '2026-01-18 15:00:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Oliver Price', 'oprice@email.com', 5, 'Worth every penny', 'Invested in a premium roofing system with upgraded underlayment and ridge vent. Lone Star explained why each upgrade mattered and the final product is impressive.', 'approved', 1, '2026-02-02 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'lone-star-roofing-and-construction'), NULL, 'Patricia Chang', 'pchang@email.com', 3, 'Good work, slow start', 'The roof looks great and the GAF warranty coverage is excellent. My only issue was the project started a week late due to material delays. They should have communicated this sooner.', 'approved', 1, '2026-02-12 14:00:00'),

-- Dallas Kitchen Design Studio (9 reviews)
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Jennifer Roberts', 'jroberts@email.com', 5, 'Magazine-worthy kitchen', 'Donald and his design team created the most beautiful kitchen I have ever seen. The custom walnut cabinets, waterfall quartz island, and professional-grade appliances are a chef''s dream.', 'approved', 1, '2025-08-25 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Michael Kim', 'mkim@email.com', 5, 'Incredible 3D design process', 'Being able to see our kitchen in 3D before construction started was amazing. We made several design changes virtually which saved time and money. The final result matched the rendering perfectly.', 'approved', 1, '2025-09-18 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Sarah Clark', 'sclark@email.com', 5, 'Best kitchen remodeler in DFW', 'We compared five companies and Dallas Kitchen Design stood out for their portfolio and design expertise. Our new kitchen has doubled the value of our home. Worth the investment.', 'approved', 1, '2025-10-12 09:15:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Brian Lopez', 'blopez@email.com', 4, 'Gorgeous countertops', 'The quartzite countertops they sourced and installed are stunning. Each slab was hand-selected and the seams are virtually invisible. Minor delay on cabinet delivery but overall very pleased.', 'approved', 1, '2025-11-08 13:00:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Helen Davis', 'hdavis@email.com', 5, 'Complete kitchen transformation', 'They knocked out a wall, relocated plumbing, rewired for new appliances, and built us a completely new kitchen. The project management was outstanding and the crew was respectful.', 'approved', 1, '2025-12-01 11:45:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Robert Santos', 'rsantos@email.com', 5, 'Dream kitchen delivered', 'From the initial consultation to the final reveal, Dallas Kitchen Design Studio exceeded our expectations at every turn. The soft-close drawers, pull-out pantry, and under-cabinet lighting are perfect.', 'approved', 1, '2025-12-20 15:30:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Alice Walker', 'awalker@email.com', 5, 'Outstanding cabinet quality', 'The custom cabinets are built to last a lifetime. Full-extension soft-close drawers, dovetail joints, and a beautiful painted finish. You can feel the quality difference.', 'approved', 1, '2026-01-10 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Martin Lee', 'mlee2@email.com', 4, 'Great kitchen, took a while', 'Our kitchen remodel took about eight weeks from demolition to completion. The quality is outstanding but we had hoped for a faster timeline. Communication was good throughout.', 'approved', 1, '2026-01-28 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'dallas-kitchen-design-studio'), NULL, 'Cynthia Harris', 'charris@email.com', 5, 'Neighbors are jealous', 'Every neighbor who has seen our new kitchen wants to know who did it. The tile backsplash, pendant lighting, and butcher block island are conversation starters. Absolutely love it.', 'approved', 1, '2026-02-10 09:00:00'),

-- Peachtree Builders Group (8 reviews)
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Marcus Brown', 'mbrown@email.com', 5, 'Custom home excellence', 'Derek and his team built our 3,500 sq ft custom home on schedule and on budget. The quality of construction, from the foundation to the finishes, is exceptional.', 'approved', 1, '2025-08-30 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Alicia Foster', 'afoster2@email.com', 5, 'Best GC in Atlanta', 'Peachtree managed our complete home renovation and it was a seamless experience. Weekly meetings, detailed budgets, and transparent communication throughout the project.', 'approved', 1, '2025-09-25 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Nathan Garcia', 'ngarcia@email.com', 5, 'Commercial buildout done right', 'They completed the buildout of our 5,000 sq ft office space in just six weeks. Professional project management and quality craftsmanship. Highly recommend for commercial projects.', 'approved', 1, '2025-10-18 10:15:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Sharon Williams', 'swilliams@email.com', 4, 'Major renovation success', 'Renovated our 1940s Decatur home with modern updates while preserving the character. A few change orders along the way but the team handled them efficiently.', 'approved', 1, '2025-11-12 13:00:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Edward Thompson', 'ethompson@email.com', 5, 'Addition perfectly matches', 'They added a 600 sq ft family room and the addition matches the existing house so perfectly you would never know it was added later. Incredible attention to architectural detail.', 'approved', 1, '2025-12-05 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Rosa Martinez', 'rmartinez@email.com', 5, 'Design-build dream team', 'Their in-house architect and project manager worked together to create and build our dream kitchen addition. The design-build approach saved us time and money compared to hiring separately.', 'approved', 1, '2025-12-28 15:00:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Christopher Young', 'cyoung@email.com', 4, 'Solid construction quality', 'Built a detached garage with a bonus room above. The construction is rock-solid and the electrical and plumbing are done right. Small punch list items were handled quickly.', 'approved', 1, '2026-01-15 11:45:00'),
((SELECT id FROM cleaners WHERE slug = 'peachtree-builders-group'), NULL, 'Diane Mitchell', 'dmitchell@email.com', 5, 'Couldn''t be happier', 'From initial concept to move-in day, Peachtree Builders delivered an outstanding experience. Our new home is everything we wanted and more. Worth every penny.', 'approved', 1, '2026-02-06 10:00:00'),

-- Charlotte Home Remodeling (8 reviews)
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Benjamin Adams', 'badams@email.com', 5, 'Whole house transformation', 'Kevin and his team remodeled our kitchen, two bathrooms, and added a screened porch. The design-build approach meant one point of contact for everything. Incredible results.', 'approved', 1, '2025-08-22 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Elizabeth Park', 'epark@email.com', 5, 'Kitchen of our dreams', 'Charlotte Home Remodeling created a stunning open-concept kitchen with custom cabinets, quartz countertops, and a gorgeous tile backsplash. The project was completed on time.', 'approved', 1, '2025-09-15 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Anthony Wright', 'awright@email.com', 5, 'Master bath renovation', 'They transformed our cramped master bathroom into a spa-like retreat with a walk-in shower, soaking tub, and double vanity. Every detail was executed perfectly.', 'approved', 1, '2025-10-20 11:15:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Grace Peterson', 'gpeterson@email.com', 4, 'Great remodeler', 'Had our entire main floor remodeled including new flooring, paint, and recessed lighting. The quality is excellent. Minor hiccup with a backordered light fixture but they handled it well.', 'approved', 1, '2025-11-25 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Philip Morris', 'pmorris@email.com', 5, 'Addition done right', 'They built a 500 sq ft addition for a home office and guest suite. The addition blends perfectly with our existing home and the quality of work is outstanding.', 'approved', 1, '2025-12-12 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Martha Collins', 'mcollins@email.com', 5, 'Repeat customer', 'This is our second project with Charlotte Home Remodeling. They remodeled our guest bathroom five years ago and just finished a beautiful kitchen renovation. Consistently excellent.', 'approved', 1, '2026-01-06 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Howard Kim', 'hkim@email.com', 4, 'Professional and skilled', 'Renovated our basement into a family room with a wet bar. The waterproofing and finishing work were done to a high standard. Some scheduling delays but the end result is great.', 'approved', 1, '2026-01-22 15:30:00'),
((SELECT id FROM cleaners WHERE slug = 'charlotte-home-remodeling'), NULL, 'Judith Clark', 'jclark@email.com', 5, 'Best in Charlotte', 'After researching dozens of remodelers in Charlotte, we chose this company and could not be happier. Their portfolio spoke for itself and our kitchen remodel exceeded even those high expectations.', 'approved', 1, '2026-02-08 11:00:00'),

-- Mile High Roofing & Gutters (7 reviews)
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Andrew Nelson', 'anelson@email.com', 5, 'Hail damage repair experts', 'Denver had terrible hail last spring and Ben''s team replaced our entire roof. They handled the insurance claim process and made it completely painless. New roof looks fantastic.', 'approved', 1, '2025-09-10 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Jessica Lee', 'jlee@email.com', 5, 'Great gutter installation', 'New seamless gutters with leaf guards have solved our ice dam problems. The install was clean and the downspouts are properly routed away from our foundation. Excellent work.', 'approved', 1, '2025-10-22 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'David Moore', 'dmoore@email.com', 4, 'Good metal roof', 'Installed a standing seam metal roof on our mountain home. It looks great and handles the snow load well. Price was higher than shingles but the longevity makes it worthwhile.', 'approved', 1, '2025-11-18 09:15:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Kimberly Foster', 'kfoster2@email.com', 5, 'Saved us on insurance claim', 'Ben met with our insurance adjuster and identified damage they initially missed. Ended up with a full roof replacement covered by insurance. Could not have navigated this without them.', 'approved', 1, '2025-12-08 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Roger Williams', 'rwilliams@email.com', 5, 'Roof and gutters together', 'Having one company handle both the roof replacement and gutter installation made the project seamless. Everything was coordinated perfectly and completed in four days.', 'approved', 1, '2026-01-02 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Tammy Brooks', 'tbrooks2@email.com', 4, 'Quality workmanship', 'Replaced our aging shingle roof with impact-resistant Class 4 shingles. The work was done well and the price was competitive. Got an insurance discount for the upgrade too.', 'approved', 1, '2026-01-20 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'mile-high-roofing-and-gutters'), NULL, 'Russell Garcia', 'rgarcia2@email.com', 5, 'Denver''s best roofer', 'Third time using Mile High for different properties and they deliver consistent quality every time. Professional crew, transparent pricing, and outstanding warranties.', 'approved', 1, '2026-02-06 15:00:00'),

-- Philly Home Renovations (7 reviews)
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Angela Murphy', 'amurphy@email.com', 5, 'Rowhome renovation specialists', 'Nick and his team completely renovated our 1920s rowhome. They preserved the original hardwood floors, brick walls, and character while updating everything else. Stunning result.', 'approved', 1, '2025-08-28 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Patrick Sullivan', 'psullivan@email.com', 5, 'Complete gut renovation', 'Bought a fixer-upper in Fishtown and Philly Home Renovations transformed it from top to bottom. New kitchen, two new bathrooms, refinished floors, and modern electrical throughout.', 'approved', 1, '2025-09-20 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Monica Ross', 'mross@email.com', 5, 'Historic restoration excellence', 'They restored our Victorian home in West Philadelphia with incredible attention to historical detail. New period-appropriate moldings, restored original staircase, and a sympathetic addition.', 'approved', 1, '2025-10-25 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'George White', 'gwhite@email.com', 4, 'Great kitchen remodel', 'Opened up our galley kitchen and created a modern open-concept space. The structural work was handled expertly and the kitchen design is beautiful. A couple of punch list items took longer than expected.', 'approved', 1, '2025-11-18 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Linda Harris', 'lharris@email.com', 5, 'Basement conversion', 'They converted our basement into a rental apartment complete with kitchen, bathroom, and separate entrance. All permits pulled and inspections passed. The rental income is paying for the renovation.', 'approved', 1, '2025-12-10 13:15:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Roy Chen', 'rochen@email.com', 4, 'Structural repair done right', 'Our rowhome had a structural issue with the party wall. Nick''s team brought in a structural engineer, got the proper permits, and repaired everything correctly. Peace of mind restored.', 'approved', 1, '2026-01-08 10:45:00'),
((SELECT id FROM cleaners WHERE slug = 'philly-home-renovations'), NULL, 'Gloria Martinez', 'gmartinez@email.com', 5, 'Whole-house renovation', 'A massive project completed on time and close to budget. Three floors renovated, all new mechanicals, and beautiful finishes throughout. Nick was available whenever we had questions.', 'approved', 1, '2026-02-01 15:00:00'),

-- Remaining cleaners with fewer reviews

-- LA Decks & Outdoor Living (5 reviews)
((SELECT id FROM cleaners WHERE slug = 'la-decks-and-outdoor-living'), NULL, 'Victor Ellis', 'vellis@email.com', 5, 'Gorgeous composite deck', 'Steven and his crew built a beautiful 600 sq ft Trex deck with built-in benches and a pergola. It is our favorite spot in the house now. Incredible outdoor living space.', 'approved', 1, '2025-10-08 10:30:00'),
((SELECT id FROM cleaners WHERE slug = 'la-decks-and-outdoor-living'), NULL, 'Nina Howard', 'nhoward@email.com', 4, 'Great outdoor kitchen', 'Built an outdoor kitchen with a built-in grill, sink, and bar area. The stonework looks professional and the functionality is exactly what we wanted.', 'approved', 1, '2025-11-15 14:00:00'),
((SELECT id FROM cleaners WHERE slug = 'la-decks-and-outdoor-living'), NULL, 'Carl West', 'cwest@email.com', 5, 'Perfect patio cover', 'The aluminum patio cover they installed keeps our backyard comfortable even in the summer heat. Great design that complements our home architecture.', 'approved', 1, '2025-12-20 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'la-decks-and-outdoor-living'), NULL, 'Heather Price', 'hprice@email.com', 4, 'Nice deck renovation', 'Replaced our old wood deck boards with composite and it looks brand new. Would have liked faster scheduling but the quality of work was excellent.', 'approved', 1, '2026-01-12 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'la-decks-and-outdoor-living'), NULL, 'Douglas Kim', 'dkim@email.com', 4, 'Good pergola construction', 'The cedar pergola they built is beautiful and well-constructed. Minor issue with one post alignment that was corrected quickly. Overall happy with the result.', 'approved', 1, '2026-02-03 15:45:00'),

-- SF Tile & Flooring (7 reviews)
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Sandra Kim', 'skim@email.com', 5, 'Beautiful hardwood floors', 'Jason and his team installed white oak hardwood throughout our main floor. The wood selection was gorgeous and the installation is flawless. Our home was transformed.', 'approved', 1, '2025-09-08 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Bruce Nelson', 'bnelson@email.com', 5, 'Expert tile work', 'Had large format porcelain tiles installed in our kitchen and entryway. The layout, cuts, and grouting are all perfect. These guys really know tile.', 'approved', 1, '2025-10-25 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Phyllis Baker', 'pbaker@email.com', 4, 'Good LVP installation', 'Installed luxury vinyl plank throughout our rental property. Durable, waterproof, and looks like real wood. Fair pricing and neat installation.', 'approved', 1, '2025-11-20 11:15:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Wayne Foster', 'wfoster2@email.com', 5, 'Floor refinishing magic', 'They refinished our 80-year-old original hardwood floors and they look like new. The dustless sanding system they use kept our house surprisingly clean during the process.', 'approved', 1, '2025-12-15 09:30:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Marie Santos', 'msantos2@email.com', 5, 'Natural stone expertise', 'Installed marble tile in our master bathroom and the result is breathtaking. They handled the material with great care and the pattern layout is gorgeous.', 'approved', 1, '2026-01-08 13:00:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Harold Green', 'hgreen@email.com', 4, 'Solid flooring company', 'Replaced carpet with engineered hardwood in three bedrooms. The team was efficient and the floors look beautiful. One transition strip needed adjustment but was fixed promptly.', 'approved', 1, '2026-01-25 10:45:00'),
((SELECT id FROM cleaners WHERE slug = 'sf-tile-and-flooring'), NULL, 'Janet Collins', 'jcollins@email.com', 5, 'Incredible shower tile', 'Custom mosaic tile work in our shower is a true work of art. The design they created is exactly what we envisioned. These are real craftsmen.', 'approved', 1, '2026-02-10 15:00:00'),

-- Chicago Roofing Authority (7 reviews)
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Dennis Walsh', 'dwalsh@email.com', 5, 'Built for Chicago winters', 'Edward and his team installed a new roof with ice and water shield and proper ventilation. We made it through our first winter with zero ice dam issues. Money well spent.', 'approved', 1, '2025-09-12 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Christine Kelly', 'ckelly@email.com', 5, 'Reliable and professional', 'Had our flat garage roof replaced with a modified bitumen system. The crew worked through cold weather and the result is watertight. Great experience.', 'approved', 1, '2025-10-18 14:30:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Larry Johnson', 'ljohnson@email.com', 4, 'Good siding installation', 'In addition to our roof, they installed new vinyl siding. Both projects were coordinated well and the house looks completely refreshed. Minor color matching issue on one panel was fixed.', 'approved', 1, '2025-11-22 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Pamela Rodriguez', 'prodriguez@email.com', 5, 'Emergency tarping in a snowstorm', 'A tree branch punched through our roof during a winter storm and their emergency crew was there within an hour. In the snow. They tarped the hole and prevented major water damage.', 'approved', 1, '2025-12-30 17:30:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Oscar Lee', 'olee@email.com', 5, 'Standing seam metal perfection', 'Beautiful charcoal gray standing seam metal roof on our modern home. The clean lines and quality of the installation are perfect. This roof will outlast us.', 'approved', 1, '2026-01-08 11:00:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Teresa Cooper', 'tcooper@email.com', 4, 'Solid gutter replacement', 'Replaced all our gutters and downspouts with oversized seamless aluminum. The new system handles heavy rain much better. Good value and professional installation.', 'approved', 1, '2026-01-22 13:30:00'),
((SELECT id FROM cleaners WHERE slug = 'chicago-roofing-authority'), NULL, 'Vincent Murphy', 'vmurphy@email.com', 5, 'Best roofer in Chicagoland', 'Edward''s company has now done three roofing projects for me across different properties. Consistently excellent work, competitive pricing, and they truly stand behind their warranty.', 'approved', 1, '2026-02-05 10:00:00'),

-- Austin Home Renovations (7 reviews)
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Rachel Foster', 'rfoster@email.com', 5, 'Complete home transformation', 'Jose and his team renovated our 1970s ranch house into a modern open-concept gem. They used sustainable materials and the energy efficiency improvements are already saving us money.', 'approved', 1, '2025-09-05 10:00:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Tyler Adams', 'tadams@email.com', 5, 'ADU construction experts', 'They built a beautiful 450 sq ft accessory dwelling unit in our backyard. Perfect for rental income and the construction quality is the same as a full-size home.', 'approved', 1, '2025-10-15 14:15:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Megan Clark', 'mclark@email.com', 5, 'Open concept conversion', 'Removed a load-bearing wall between our kitchen and living room and the transformation is incredible. The structural beam was handled perfectly and the space feels huge now.', 'approved', 1, '2025-11-20 11:30:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Brandon Davis', 'bdavis@email.com', 4, 'Great renovation company', 'Renovated two bathrooms and a laundry room. Quality work throughout with attention to detail. Minor delay on tile delivery but otherwise a smooth process.', 'approved', 1, '2025-12-18 09:00:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Olivia Martin', 'omartin@email.com', 5, 'Sustainable building experts', 'Love that they focus on green building practices. They used reclaimed wood, low-VOC paints, and energy-efficient windows throughout our renovation. The house is healthier and greener.', 'approved', 1, '2026-01-10 13:45:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Nathan White', 'nwhite2@email.com', 4, 'Solid work on our addition', 'Added a sunroom and master closet to our home. The work is high quality and the addition integrates seamlessly. Budget ran slightly over due to material cost increases.', 'approved', 1, '2026-01-28 10:15:00'),
((SELECT id FROM cleaners WHERE slug = 'austin-home-renovations'), NULL, 'Sophia Johnson', 'sjohnson@email.com', 5, 'Highly recommend', 'Jose and his team are honest, talented, and professional. Our whole-house renovation was a huge undertaking and they managed it beautifully. Our Austin home is now our forever home.', 'approved', 1, '2026-02-10 15:30:00');

SET FOREIGN_KEY_CHECKS = 1;
